export const GAME_DATA = [
  { id: 1, name: 'Subway Surfers', genres: ['Idle/Hypercasual', 'Runner'], traits: ['Casual', 'Single Player', 'Action'], platform: 'Mobile', premiumness: 1 },
  { id: 2, name: 'Temple Run', genres: ['Idle/Hypercasual', 'Runner'], traits: ['Casual', 'Single Player', 'Action'], platform: 'Mobile', premiumness: 1 },
  { id: 3, name: 'Candy Crush Saga', genres: ['Puzzle', 'Idle/Hypercasual'], traits: ['Casual', 'Single Player', 'Relaxing'], platform: 'Mobile', premiumness: 1 },
  { id: 4, name: 'Angry Birds', genres: ['Puzzle', 'Idle/Hypercasual'], traits: ['Casual', 'Single Player'], platform: 'Mobile', premiumness: 1 },
  { id: 5, name: 'BitLife', genres: ['Simulation'], traits: ['Casual', 'Single Player', 'Story Driven', 'Text Based'], platform: 'Mobile', premiumness: 1 },
  { id: 6, name: 'Shadow Fight 2/3/4', genres: ['Fighting', 'Action'], traits: ['Single Player', 'Story Driven'], platform: 'Mobile', premiumness: 1 },
  { id: 7, name: 'Ludo King', genres: ['Board Game', 'Social/Party'], traits: ['Casual', 'Multiplayer'], platform: 'Mobile', premiumness: 1 },
  { id: 8, name: 'Among Us', genres: ['Social/Party'], traits: ['Casual', 'Multiplayer'], platform: 'Mobile', premiumness: 1 },
  { id: 9, name: '8 Ball Pool', genres: ['Sports'], traits: ['Casual', 'Multiplayer', 'Relaxing'], platform: 'Mobile', premiumness: 1 },
  { id: 10, name: 'Stumble Guys / Fall Guys', genres: ['Social/Party', 'Action'], traits: ['Casual', 'Multiplayer'], platform: 'Mobile', premiumness: 1 },
  { id: 11, name: 'BGMI / PUBG Mobile', genres: ['Shooter', 'Battle Royale'], traits: ['Competitive', 'Multiplayer'], platform: 'Mobile', premiumness: 2 },
  { id: 12, name: 'Free Fire', genres: ['Shooter', 'Battle Royale'], traits: ['Competitive', 'Multiplayer', 'Casual'], platform: 'Mobile', premiumness: 2 },
  { id: 13, name: 'Call of Duty Mobile', genres: ['Shooter', 'Battle Royale'], traits: ['Competitive', 'Multiplayer'], platform: 'Mobile', premiumness: 2 },
  { id: 14, name: 'COD Modern Warfare / Warzone', genres: ['Shooter'], traits: ['Competitive', 'Multiplayer', 'Story Driven', 'Cinematic'], platform: 'PC/Console', premiumness: 4 },
  { id: 15, name: 'Valorant', genres: ['Shooter', 'Strategy'], traits: ['Competitive', 'Multiplayer'], platform: 'PC', premiumness: 3 },
  { id: 16, name: 'Counter Strike 2 / CS GO', genres: ['Shooter'], traits: ['Competitive', 'Multiplayer'], platform: 'PC', premiumness: 3 },
  { id: 17, name: 'Fortnite', genres: ['Shooter', 'Battle Royale', 'Creative'], traits: ['Casual', 'Multiplayer'], platform: 'Both', premiumness: 2 },
  { id: 18, name: 'Apex Legends', genres: ['Shooter', 'Battle Royale'], traits: ['Competitive', 'Multiplayer'], platform: 'PC/Console', premiumness: 3 },
  { id: 19, name: 'Battlefield', genres: ['Shooter'], traits: ['Competitive', 'Multiplayer', 'Team Based', 'Cinematic'], platform: 'PC/Console', premiumness: 4 },
  { id: 20, name: 'GTA V / GTA San Andreas', genres: ['Open World', 'Shooter'], traits: ['Story Driven', 'Multiplayer', 'Cinematic'], platform: 'PC/Console', premiumness: 4 },
  { id: 21, name: 'Red Dead Redemption 2', genres: ['Open World', 'Action'], traits: ['Story Driven', 'Single Player', 'Cinematic'], platform: 'PC/Console', premiumness: 5 },
  { id: 22, name: 'Far Cry', genres: ['Open World', 'Shooter'], traits: ['Story Driven', 'Single Player', 'Survival'], platform: 'PC/Console', premiumness: 4 },
  { id: 23, name: 'Assassin\'s Creed', genres: ['Open World', 'Action', 'RPG'], traits: ['Story Driven', 'Single Player'], platform: 'PC/Console', premiumness: 4 },
  { id: 24, name: 'Prince of Persia', genres: ['Action', 'Platformer'], traits: ['Story Driven', 'Single Player', 'Puzzle'], platform: 'PC/Console', premiumness: 3 },
  { id: 25, name: 'Tomb Raider', genres: ['Action', 'Open World'], traits: ['Story Driven', 'Single Player', 'Puzzle', 'Exploration'], platform: 'PC/Console', premiumness: 4 },
  { id: 26, name: 'God of War', genres: ['Action'], traits: ['Story Driven', 'Single Player', 'Cinematic'], platform: 'PC/Console', premiumness: 5 },
  { id: 27, name: 'Ghost of Tsushima', genres: ['Open World', 'Action', 'RPG'], traits: ['Story Driven', 'Single Player', 'Cinematic'], platform: 'PC/Console', premiumness: 5 },
  { id: 28, name: 'The Witcher 3', genres: ['RPG', 'Open World'], traits: ['Story Driven', 'Single Player', 'Cinematic'], platform: 'PC/Console', premiumness: 5 },
  { id: 29, name: 'Skyrim / Elder Scrolls', genres: ['RPG', 'Open World'], traits: ['Story Driven', 'Single Player', 'Creative'], platform: 'PC/Console', premiumness: 4 },
  { id: 30, name: 'Elden Ring / Dark Souls', genres: ['RPG', 'Action'], traits: ['Challenging', 'Single Player'], platform: 'PC/Console', premiumness: 5 },
  { id: 31, name: 'Genshin Impact / Honkai Star Rail', genres: ['RPG', 'Action'], traits: ['Story Driven', 'Single Player', 'Open World', 'Gacha'], platform: 'Both', premiumness: 3 },
  { id: 32, name: 'Pokemon GO / Pokemon', genres: ['RPG'], traits: ['Casual', 'Single Player', 'Collecting', 'Open World'], platform: 'Both', premiumness: 2 },
  { id: 33, name: 'Minecraft', genres: ['Creative', 'Open World', 'Survival'], traits: ['Casual', 'Multiplayer', 'Single Player'], platform: 'Both', premiumness: 2 },
  { id: 34, name: 'Roblox', genres: ['Creative', 'Social/Party'], traits: ['Casual', 'Multiplayer'], platform: 'Both', premiumness: 1 },
  { id: 35, name: 'Sea of Thieves', genres: ['Open World', 'Action', 'Social/Party'], traits: ['Multiplayer', 'Exploration', 'Survival'], platform: 'PC/Console', premiumness: 4 },
  { id: 36, name: 'Rust', genres: ['Survival', 'Open World'], traits: ['Competitive', 'Multiplayer', 'Challenging'], platform: 'PC', premiumness: 4 },
  { id: 37, name: 'Subnautica', genres: ['Survival', 'Open World'], traits: ['Single Player', 'Exploration', 'Relaxing'], platform: 'PC/Console', premiumness: 4 },
  { id: 38, name: 'Granny / Outlast / Resident Evil', genres: ['Horror', 'Action'], traits: ['Single Player', 'Challenging', 'Story Driven'], platform: 'Both', premiumness: 3 },
  { id: 39, name: 'FIFA / EA FC', genres: ['Sports', 'Simulation'], traits: ['Competitive', 'Multiplayer'], platform: 'Both', premiumness: 3 },
  { id: 40, name: 'Real Cricket / Cricket 19/22/24', genres: ['Sports', 'Simulation'], traits: ['Single Player', 'Competitive'], platform: 'Both', premiumness: 2 },
  { id: 41, name: 'Need for Speed', genres: ['Racing', 'Action'], traits: ['Single Player', 'Open World'], platform: 'PC/Console', premiumness: 4 },
  { id: 42, name: 'Asphalt 9', genres: ['Racing', 'Action'], traits: ['Casual', 'Single Player'], platform: 'Mobile', premiumness: 2 },
  { id: 43, name: 'Rocket League / Sideswipe', genres: ['Sports', 'Racing', 'Action'], traits: ['Competitive', 'Multiplayer'], platform: 'Both', premiumness: 2 },
  { id: 44, name: 'Clash of Clans / Clash Royale', genres: ['Strategy', 'Card/Board'], traits: ['Competitive', 'Casual', 'Multiplayer', 'Base Building'], platform: 'Mobile', premiumness: 2 },
  { id: 45, name: 'Plants vs Zombies', genres: ['Strategy'], traits: ['Casual', 'Single Player'], platform: 'Mobile', premiumness: 1 },
  { id: 46, name: 'Lords Mobile / Rise of Kingdoms', genres: ['Strategy'], traits: ['Competitive', 'Multiplayer', 'Base Building'], platform: 'Mobile', premiumness: 2 },
  { id: 47, name: 'Civilization VI / Age of Empires', genres: ['Strategy'], traits: ['Single Player', 'Multiplayer', 'Challenging', 'Competitive'], platform: 'PC', premiumness: 4 },
  { id: 48, name: 'Hearts of Iron IV / Crusader Kings III', genres: ['Strategy', 'Simulation'], traits: ['Single Player', 'Challenging', 'Story Driven', 'Complex'], platform: 'PC', premiumness: 5 },
  { id: 49, name: 'Rimworld / Manor Lords / Norland', genres: ['Strategy', 'Simulation'], traits: ['Single Player', 'Creative', 'Complex', 'Survival', 'Base Building'], platform: 'PC', premiumness: 5 },
  { id: 50, name: 'Mobile Legends / Wild Rift / Dota 2 / LoL', genres: ['MOBA'], traits: ['Competitive', 'Multiplayer', 'Strategy', 'Team Based', 'Challenging'], platform: 'Both', premiumness: 3 }
];
